version: '3.4'

services:
  finaktivaeventlogs.api:
    image: ${DOCKER_REGISTRY-}finaktivaeventlogsapi
    build:
      context: .
      dockerfile: FinaktivaEventLogs.API/Dockerfile
networks:
  default:
    external:
         name: microservicesnetwork